version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-type: "direct:production"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
