version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    allow:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
